### ISSUE TITLE
Is there an alternative way to access your dataset?

### ISSUE THREAD

**Issue by EverRaynor** [eduardo-candioto-fidelis/raw-radar-data-generation#1]
Hello, the size of your dataset is quite large, and downloading it via Git LFS can be costly. Is there an alternative way to access your dataset? Thanks.

**Comment by eduardo-candioto-fidelis** [comment]
Hello! I put the dataset in [kaggle](https://www.kaggle.com/datasets/eduardocandioto/raw-radar-data?select=EXP_17_M.h5). Check if you can access it.

**Comment by EverRaynor** [comment]
Thank you for making the dataset more accessible for download. I also encountered the same issue when downloading the model 'model-19fh3wpc-epoch-4655.h5.' Would it be possible to upload the model to Kaggle? Thank you

**Comment by eduardo-candioto-fidelis** [comment]
Of course, I've put it in the same link.
